### ISSUE TITLE
Add start time, end time and duration restrictions for the class, TimeInterval

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#964] opened 2023-09-12 02:36 UTC
I suggest adding three subclass restrictions as follows:
- `gist:startDateTime some xsd:dateTime` 
- `gist:endDateTime some xsd:dateTime`
- `hasMagnitude some gist:Duration`

This directly echos the text definition below from version 12.0.0
```
gist:TimeInterval
	a owl:Class ;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	skos:definition "A span of time with a known start time, end time, and duration. As long as two of the three are known, the third can be inferred."^^xsd:string ;
	skos:example "7pm to 9pm on Jan 1, 2001; fiscal year 2023; the week starting at midnight of January 12, 2023 and lasting exactly 168 hours."^^xsd:string ;
	skos:prefLabel "Time Interval"^^xsd:string ;
	skos:scopeNote
		"An ongoing state of affairs with an unknown end time in the future cannot be a time interval; e.g. the lifespan of a living person cannot be a time interval, as the end time is unknown."^^xsd:string ,
		"This is distinct from a gist:Duration, which describes how long a time interval lasts (e.g., one hour; 3 days; 22 minutes)."^^xsd:string
		;
	.
```

**Comment by Jamie-SA** [comment] 2023-09-12 03:55
Is this a duplicate of #925 ?

**Comment by rjyounes** [comment] 2023-09-12 12:47
Duplicates #925.

**Closed by rjyounes** 2023-09-12 12:47 UTC
