### ISSUE TITLE
decimalValue misleadingly suggests that the range would be xsd:decimal

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#172] opened 2020-02-12 19:33 UTC
One would expect that a property named decimalValue would have  xsd:decimal as its range. It does not.  The range is now xsd:double.

FIX: change the name to doubleValue or change the range to xsd:decimal.

This future-proofing allows for other properties that may need to point to particular datatypes.  E.g. floatValue, integerValue etc.

See also https://github.com/semanticarts/gist/issues/171

**Comment by Jamie-SA** [comment] 2021-05-14 18:33
No one commented on this so I don't know if that means there is no support for it, or everyone agreed with it.
Should we consider this for the v10 release?

**Comment by rjyounes** [comment] 2021-05-25 20:05
@uscholdm @Jamie-SA Are this and #171 the same or different? If the same, please combine them.

**Comment by Jamie-SA** [comment] 2021-05-25 22:53
@rjyounes the title of these two issues address different problems, but I think @uscholdm 's 2nd suggestion in #171 covers the solution for this issue as well.

I don't see that we need 2 issues for this. I could see closing this issue and changing the title of 171 to include fixing all problems with gist:decimalValue if you wanted to go that route.

**Comment by uscholdm** [comment] 2021-05-26 00:54
That makes sense to me.

**Comment by rjyounes** [comment] 2021-05-27 15:41
Duplicate of #171.

**Closed by rjyounes** 2021-05-27 15:41 UTC
Labels: closed: duplicate
