### ISSUE TITLE
contributesTo property is far too narrow

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#465] opened 2021-04-29 00:35 UTC
The definition of `contributesTo` is: `The parts of a system contribute to the goal/ function of the whole system`.  This excludes a common use:  to be a contributing author of a document.  I was unable to use it for a client ontology because of that.  There are many other notions of contribution that have nothing to do with parts or goals of systems. The current definition is more fitting for a property called `facilitatesAchievementOf`

PROPOSAL:  
- change the definition of the property to be more generic (look in the dictionary)
- don't have a special property for contributing to the goal of a system, just use the generic `contributesTo`
- ALTERNATIVE:  create a subproperty of `contributesTo` for the more specific meaning.

```
gist:contributesTo
	a owl:ObjectProperty ;
	skos:definition "The parts of a system contribute to the goal/ function of the whole system"^^xsd:string ;
	skos:prefLabel "contributes to"^^xsd:string ;
	.
```

**Comment by rjyounes** [comment] 2021-09-16 14:31
Duplicate of #572

**Closed by rjyounes** 2021-09-16 14:31 UTC
Labels: closed: duplicate, topic: annotations
