### ISSUE TITLE
Remove default prefix

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#958] opened 2023-08-24 21:10 UTC
The first line in gistCore.ttl is:
- `@prefix : <https://w3id.org/semanticarts/ontology/gistCore#> .`

We regard it as bad practice to use a default namespace, and if we did want one, it would not be the ontology IRI with the slash replaced by a hash. If this is added automatically, then perhaps we should strip it off?

**Comment by rjyounes** [comment] 2023-08-29 19:01
It would be easier to define it ourselves than strip it out each time; that would at least make it correct. Though we could add it to the pre-commit hook to strip out - the way we used to strip out SKOS stub declarations and will no longer do.

For my own information why is it bad practice to use a default namespace? Note that we are not actually using it, just defining it - though I don't know if that changes matters.

**Comment by Jamie-SA** [comment] 2023-11-09 15:35
Duplicate of #898

**Closed by Jamie-SA** 2023-11-09 15:35 UTC
