### ISSUE TITLE
duplicate object property assertions causing code problems

### ISSUE THREAD

**Issue by DougalW** [semanticarts/gist#298] opened 2020-05-27 05:12 UTC
Hi, when I run our enterprise ontology through our schema service, we get problems with the following GIST classes:

- Duplicate relationship property definition for hasMagnitude on class PhysicalIdentifiableItem with types Weight and Volume 
- Duplicate relationship property definition for hasMagnitude on class PhysicalSubstance with types Weight and Volume

We can't build and manipulate objects from classes that have duplicate object properties pointing to different class types.

Would it be possible to modify these to something like e.g.:

`'Has Magnitude' some (Volume or Weight)`

**Comment by uscholdm** [comment] 2020-06-02 06:15
I don't understand what the problem is. The meaning of these axioms says that  every instance of PhysicalIdentifiableItem  and every instance of PhysicalSubstance  has a Volume and also has a Weight. This is the correct way to model this in OWL.  We don't mean that it might have Weight but no Volume or Volume but no Weight. Both are always present.  That would be a good trick though, you could clean up in the weight-watching industry. :-)

My guess is that your schema service makes different assumptions that OWL does and they are incompatible.

**Comment by DougalW** [comment] 2020-06-02 09:00
The end goal of our schema service is to be able to provide a schema that can be used by language constructs from java, javascript/json, dot net, etc to present data to/from a semantic graph.  Our schema service does not support duplicate property (attribute and relationship) names to make an OWL schema usable by current programming languages to validate the data.

All languages have a structure construct where the LHS name must be unique, and in strongly typed languages the RHS type definition has a one-to-one relationship with the name on the LHS.

The PhysicalIdentifiable may well be able to have both Weight and Volume magnitude as indicated by the double  `hasMagnitude` object property. While that may work in owl constructs it cannot be supported by anything other than untyped data in standard programming languages.

Modelling of the above dual hasMagnitude information is still possible, for example
1. by simply providing two magnitude attributes hasWeightMagnitue and hasVolumeMagnitude to distinguish
2. by providing a single hasMagnitude property with a union class combining the above two types - `hasMagnitude some (Volume and Weight)`

**Comment by DougalW** [comment] 2020-06-02 09:02
BTW, if I'm missing something and there's a better way to instantiate an object in Java from an OWL construct with multiple instances of the same object property, I'm all ears :)

**Comment by rjyounes** [comment] 2020-06-02 14:28
As long as our OWL is valid and accurately reflects the semantics we are trying to express, there is no gist issue here. I suggest closing this issue.

**Comment by DougalW** [comment] 2020-06-02 21:19
This issue might effect uptake of GIST and it is easy to solve. It's likely to come up again as GIST is more widely adopted and software is built to consume ontologies based on GIST.

The classes `PhysicalSubstance` and `PhysicalIdentifiableItem` are the only classes in GIST with this issue, and they can easily be converted to be defined classes:

PhysicalSubstance - `('Has Magnitude' some Volume) and ('Has Magnitude' some Weight)`

PhysicalIdentifiableItem - `('Has Magnitude' some Volume) and ('Has Magnitude' some Weight) and ('Identified By' some ID) and ('Made Up Of' some 'Physical Substance')`

**Comment by rjyounes** [comment] 2020-06-02 21:31
PhysicalIdentifiableItem is not an object with an ID, it is a physical object in opposition to a substance, where items can be differentiated from one another as opposed to an undifferentiated mass - basically the difference between count and mass nouns. E.g., water is a PhysicalSubstance, table is a PhysicalIdentifiableItem.

madeUpOf some PhysicalSubstance is probably correct, so we can review that.

**Comment by uscholdm** [comment] 2020-06-03 00:47
RI agree with Rebecca:  I don't see that the issue is with gist, 
> As long as our OWL is valid and accurately reflects the semantics we are trying to express

It is true in this case.

**Comment by DougalW** [comment] 2020-06-03 02:51
I guess what I'm asking is that for these two classes (which are the only ones with this issue), can you change them to be defined classes? The semantics will be the same and there will be no change in meaning, but they are then compatible with Jena and Java.

**Comment by uscholdm** [comment] 2020-06-03 06:11
The semantics is not the same. Using a defined class sanctions inference into the class, which is not currently the case.  I am not a developer, so I have no idea what the problem is that you are experiencing.  Can you clearly explain exactly what the problem is, so that our developers can evaluate the situation?

**Comment by Jamie-SA** [comment] 2020-06-03 06:14
@rjyounes I think the owl in Dougal's message [^above^](https://github.com/semanticarts/gist/issues/298#issuecomment-637812415) is mostly from gist, the current gist does include ID and madeUpOf in the restrictions for PhysicalIdentifiableItem.

@DougalW I am a developer not an ontologist so my OWL is not real strong and I might not fully understand your argument or all of the differences. If your request doesn't change the semantics or meaning, then a parser that isn't generating the same result between the two seems like you could say it has a bug. Although I recognize different parsers have different technical limitations.

I am also unsure because you last comment seems different than your first request but maybe that is my lack of understanding OWL.

I see Michael also commented while I was writing this... and I agree, I am trying to understand why making them defined classes would fix the parsing.

**Comment by DougalW** [comment] 2020-06-03 07:23
@uscholdm - I didn't think of the inference issue, that's a great point.

@JG - we have created an enterprise ontology that uses GIST as an upper ontology. We use this enterprise ontology in our software platform to perform integration, governance and analytics use cases. This part of our platform is all written in Java.

Because our platform is based on Java above the semantics / data layer, we use Jena to marshal objects out of our enterprise ontology and interact with the AWS Neptune triplestore. When we update the ontology (e.g. a new version of GIST is released or I modify our ontology), our schema service uses Jena to update an in-memory object-oriented representation of the ontology that is suitable for use by Java and our front-end (React) to action these use cases.

Jena loads our enterprise ontology, which declares GIST as an import, and builds an object oriented representation of the ontology as per the Jena documentation (https://jena.apache.org/documentation/ontology/). When Jena loads either the GIST `PhysicalSubstance` or `PhysicalIdentifiableItem` class, one of the two hasMagnitude restrictions on those classes are ignored, whichever is seen last.  Unfortunately, due to the behaviour of java hash sets/maps this behaviour is random.

Essentially, for an OO language like Java, any OWL/RDF parsing software can't see OWL object properties that are named the same thing and point to two distinct types - in this case `'Has Magnitude' some Volume` and `'Has Magnitude' some Weight`, which are declared on both these classes.

This is an issue that will affect uptake of GIST for anyone who uses a typed modern programming language (e.g. Java, .Net) and software to parse RDF/OWL into an object model (e.g. using Jena, RDF4J or the OWL API). It's currently only experienced with these two classes  in GIST (and any others you might create like this in the future).

There are three possible work arounds:

1. - you could modify the `'Has Magnitude'` object property on both classes in some way that preserves your semantic intent, and either amalgamate them (e.g. `'Has Magnitude' some Weight and Volume`
2. - you could use two different object properties to achieve the same semantics
3. - we (my company) could create equivalent classes with slightly different semantics (e.g. we don't really care too much about inference for these classes)

Option 3 is not great because it makes tracking your changes complex and manual, and other GIST users will have to do the same thing which might limit their willingness to use GIST.
Option 1 is preferred as it doesn't proliferate object properties and doesn't require everyone else to use option 3.
Option 2 would possibly proliferate object properties which isn't good.

I hope this explanation makes sense - it's quite hard to explain in an issue so I'm happy to have a call to discuss, and I could also bring my lead developer in to give his perspective as a deeply experienced user of Javas, our schema service and Jena.

**Comment by rjyounes** [comment] 2020-06-03 15:02
@Jamie-SA Sorry, I didn't check gist for those restrictions. I think the identifiedBy one is almost surely wrong. 

@DougalW I stand by my claim that the ontology should not be bent to accommodate the needs of specific applications. That runs counter to our data-centric approach.

**Comment by rjyounes** [comment] 2020-06-03 15:05
Added issue #306 to address the identifiedBy restriction.

**Comment by DougalW** [comment] 2020-06-03 20:25
> @DougalW I stand by my claim that the ontology should not be bent to accommodate the needs of specific applications. That runs counter to our data-centric approach.

I fully subscribe to the data-centric approach, and have for ten years. However, I think there's two ideas here that are perhaps being mixed up.

1. A usablity problem - It's possible to create semantically correct ontologies that are unusable by anyones code. This requires an ontologist to make a choice to express the semantics in a way to make an ontology consumable by end users - after all, at some point a modern development language will be required to interact with the ontology and they will all fail at this very problem because they are just not constructed to work with things like duplicate object properties with different types. There are only two classes in GIST with this problem, so its perhaps not too much effort to refactor these to avoid the problem.

2. An application-specific problem - if an integrated application expressed data in a specific way, and the user requested the ontology be bent to fit this, then this would be a very bad thing and replicate all the problems we see in the IT industry.

I am absolutely not asking for you to go down the second approach - I don't have a specific application in mind, rather all applications anyone will build now and in the future. 

By asking you to go down the first approach, I'mmnot asking for a violation of the data-centric architecture principle, rather I'm seeking a way to support it by ensuring the uptake of GIST by modern languages.

**Comment by uscholdm** [comment] 2020-06-03 20:51
We have been using gist for years and have not had any problems such as what you report. You are correct that your concern is not application-specific in the sense of an application of the ontology. However it is very tool-specific.   There seems to be something about Jena that is the root of your problem.  We create gist using correct OWL. It is up to the tool developers and users to make sure they play nice with OWL.  We could make a workaround for your problem, but it might trigger a problem with another tool that had been working for someone else.  The solution is not to fix gist, it is not broken. The solution is to fix the tool, or choose a tool that works properly.

As a workaround, you can always make changes to your local copy of gist and proceed from there.

**Comment by rjyounes** [comment] 2020-06-03 20:51
Do you have evidence that this feature of gist is "unusable by anyone's code"?

**Comment by DougalW** [comment] 2020-06-03 22:05
> We have been using gist for years and have not had any problems such as what you report. 

Can you please ask your semantic developers how they address this issue? They must have faced it and solved it somehow.

My guess is that your developers have been using some workarounds, or they have a really smart approach that I'd love to learn from. I could understand if they used document stores or key/value stores to interact with GIST, but I just cannot see how you would use strongly typed languages and not get the problems we have experienced.

> However it is very tool-specific. 

Alas, it's not tool specific (I wish it was). It's caused by the nature of modern typed development languages, which require uniqueness for data and object properties on a per-class basis. This is not a problem with our platform per-se, rather all typed development languages will have this problem.

Jena can load multiple object properties from the ontology, but it then has to be used by Java or .Net (most common languages) and that's where the problem occurs. We currently turn the Jena output into a Java map but Java is inconsistent in how it reads and writes to these constructs because of the duplication issue. We could turn them into a list or array structure but you lose type information (and OWL presents to code as very strongly multi-typed, which is great) and this will require code changes through our stack to accommodate the loss of semantics.

> The solution is not to fix gist, it is not broken

I agree it's not broken, but it is problematic for just these two classes. Can you think of a way to get the same semantics without the duplicate object property issue? What about this: `'Has Magnitude' some (Volume and Weight)`

>It is up to the tool developers and users to make sure they play nice with OWL. 

It's not a tool issue though, it's an issue of semantics but extended into the code level semantics. In principle, if you create an ontology that is semantically correct but unusable by code, how can people use it to create data centric applications?

> As a workaround, you can always make changes to your local copy of gist and proceed from there.

We have identified three workarounds - modify local GIST (makes updates problematic), create a fully separate class that duplicates the functionality with changes I'm suggesting, or modify our code to parse these two classes.

None of these are good as semantic changes in GIST itself.

**Comment by uscholdm** [comment] 2020-06-03 23:02
It seems to me you have an impedance mismatch between description logic and object-oriented programming.

**Comment by DougalW** [comment] 2020-06-04 02:51
> > Can you please ask your semantic developers how they address this issue? They must have faced it and solved it somehow.
> 
> I don't think that assumption is warranted. It seems to me you have an impedance mismatch between description logic and object-oriented programming. I hope to hear from our developers. You might also try the semantic web mailing list or other community help boards. They may have encountered the problem you are having.

Thanks Michael. I've posted to a few lists so will see what I get back. It's definitely an impedance mismatch, but not just with OO. If I want to take some output from a triplestore that conforms to PhysicalIdentifiableItem and say serialise it using JSON, then it won't work. JSON-LD supports this type of data, but its pretty much the only data representation format that does.

**Comment by uscholdm** [comment] 2020-06-04 03:24
> If I want to take some output from a triplestore that conforms to PhysicalIdentifiableItem and say serialise it using JSON, then it won't work. JSON-LD supports this type of data, but its pretty much the only data representation format that does.

Maybe that's your answer. Use JSON-LD.  OWL ontologies are represented as RDF triples and are designed to be populated using RDF triples.  I'd expect JSON-LD to work; it's a syntactic variation of RDF.

**Comment by DougalW** [comment] 2020-06-04 03:31
Unfortunately that works for serialisation Outbound and inbound to our code but not programmatic manipulation inside our code.

**Comment by DougalW** [comment] 2020-06-04 03:32
Is 'Has Magnitude' some (Volume and Weight) semantically equivalent to the current semantics?

**Comment by uscholdm** [comment] 2020-06-04 03:49
> Is 'Has Magnitude' some (Volume and Weight) semantically equivalent to the current semantics?

No. Volume and Weight are disjoint. So that is equivalent to saying 
`'Has Magnitude' some owl:Nothing`

**Comment by DougalW** [comment] 2020-06-04 06:48
> > Is 'Has Magnitude' some (Volume and Weight) semantically equivalent to the current semantics?
> 
> No. Volume and Weight are disjoint. So that is equivalent to saying
> `'Has Magnitude' some owl:Nothing`

Looking at GIST 9.2, none of the `Magnitude` sub-classes are currently disjoint. Running Pellet does not return any errors if I create a substitute class for `GIST:PhysicalIdentifiableItem` like this: `MTPhysicalIdentifiableItem 'Has Magnitude' some (Volume and Weight)`

**Comment by uscholdm** [comment] 2020-06-04 07:11
Well, that's a fair point. But it is also beside the point.  ` 'Has Magnitude' some (Volume and Weight)` literally means that the IRI that is the object of the triple using the hasMagnitude property is BOTH a Weight AND a Volume. Can you you think of a volume which IS also a weight? That makes no sense.  If it seems to make sense, then you should be able to answer to the following question: 
* How much is 3 cubic meters in kilograms? 

We probably should have that disjoint axiom in the ontology for this. 

Try it yourself. Add the disjoint axiom between Volume and create an actual instance and put it in both classes: Volume and Weight. Inference finds a logical inconsistency.

**Comment by DougalW** [comment] 2020-06-04 07:24
Now this gets in to physics. Theoretically you can have a volume with no mass (a 'perfect vacuum', except it's really impossible to achieve in practice, because even a vacuum in empty space has energy and minute amounts of mass (around a few hydrogen atoms per cubic meter). So the answer to "How much is 3 cubic meters in kilograms?" would depend on the enclosed volume. In terms of physics an enclosed volume of air has mass, hydrogen has mass, empty space has mass etc. But in an abstract sense I agree, it doesn't make a lot of sense.

But I get your point about the URI pointing to a semantically odd set of triples, and the need for duplicate object properties. So I'm very interested in how your developers support this when they create applications built on top of a semantic graph.

**Comment by rjyounes** [comment] 2020-06-05 12:02
After looking at our OWL, I'm wondering if this isn't a stylistic problem. Ignoring isIdentifiedBy and madeUpOf, we have
```
<owl:Class rdf:about="&gist;PhysicalIdentifiableItem">
        <rdfs:subClassOf>
                <owl:Restriction>
                        <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
                        <owl:someValuesFrom rdf:resource="&gist;Volume"/>
                </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:subClassOf>
                <owl:Restriction>
                        <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
                        <owl:someValuesFrom rdf:resource="&gist;Weight"/>
                </owl:Restriction>
        </rdfs:subClassOf>
<owl:Class>
```
Would your problem be fixed if this were changed to the semantically identical, stylistically different version below?

```
<owl:Class>
        <rdfs:subClassOf>
                <owl:Class>
                        <owl:intersectionOf rdf:parseType="Collection">
                                <owl:Restriction>
                                        <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
                                        <owl:someValuesFrom rdf:resource="&gist;Volume"/>
                                </owl:Restriction>
                                <owl:Restriction>
                                        <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
                                        <owl:someValuesFrom rdf:resource="&gist;Weight"/>
                                </owl:Restriction>
                        </owl:intersectionOf>
                </owl:Class>
        </rdfs:subClassOf>
</owl:Class>

```
I'm still not agreeing in principle that the ontology should be written to suit the needs of specific software applications, and it would most likely be difficult to consistently maintain one of these stylistic variants over the other in the course of future development, but I'm curious whether this would fix it. Personally I have a stylistic preference for the second version, but that's beside the point.

**Comment by Jamie-SA** [comment] 2020-06-05 15:42
@DougalW I haven't had time to digest your comments so I don't have a well thought out response to your situation. I'd be happy to have a call with you to discuss.

As for how we handle the problem in our data-centric architecture, probably the biggest one is we don't try to map RDF/OWL to OO classes or strongly typed programming constructs. The goal is to interpret the data as it exists at any point in time. It should be able to support any possible RDF construct.

As Michael said, there is an impedance mismatch between RDF/OWL's relationships and strongly typed object oriented programming. As you mentioned, there are ways around it, but the two worlds don't map well because they are fundamentally different. If you want to support all of the flexibility of RDF/OWL then your code has to be able to handle the fact that RDF/OWL lets you do this. It isn't that you can't handle it with Java, its that you have to write your software to handle it.

It sounds like your parsing isn't building the context it needs to properly interpret the data. You can't treat a few triples in isolation.

A reason you may not have experienced this problem much with other ontologies is that many Ontologists think somewhat from an OO or Relational data modeling perspective because that is what has been standard practice for so long. They will create multiple properties that fundamentally have the same meaning but connect different things. They probably think this is easier to understand. The result is you end up with 10's to 100's of thousands of terms, which is not digestible by a developer in a reasonable amount of time. I will go so far as to say that is probably an anti-pattern from Semantic Arts' perspective. If you have code behind every ontology term this results in code bloat and complexity. All of which increases maintenance and integration costs in the long run.

(Nearly) Anything is possible with software, I'd guess we can find a solution to handle this case in Java.

**Comment by Jamie-SA** [comment] 2020-06-05 16:43
@DougalW I took a quick look at the Jena link you posted and saw this:

_In an ontology, a property denotes the name of a relationship between resources, or between a resource and a data value. It corresponds to a predicate in logic representations. One interesting aspect of RDFS and OWL is that properties are not defined as aspects of some enclosing class, but are first-class objects in their own right._

That would indicate to me that Jena is fully capable of representing gist. Which is what I would expect given its widespread use.

**Comment by scotthenninger** [comment] 2020-06-05 19:29
@DougalW I'm wondering if your issue is really with the schema service that uses your "schema service uses Jena to update an in-memory object-oriented representation of the ontology that is suitable for use by Java and our front-end".  I.e. Jena may fail on the multiple object properties with different class values.  Perhaps it is assuming that these are transformed into the single object property/value pairs for processing (using and in this case).  It may be worth exploring Jena and Jena forums to see if others have similar issues.

The bottom line is that Gist is using a perfectly valid form of OWL that expresses various constraints of values of an object property.  For example, if you wanted to define a SuburbanPerson as a class of individuals that have at least one 4-wheel vehicle and one sedan vehicle, then this could be expressed as follows (in Turtle):

ex:SuburbanPerson
  rdf:type owl:Class ;
  rdfs:subClassOf ex:Person ;
  rdfs:subClassOf [
      rdf:type owl:Restriction ;
      owl:onProperty ex:hasVehicle ;
      owl:someValuesFrom ex:FourWheelVehicle ;
    ] ;
  rdfs:subClassOf [
      rdf:type owl:Restriction ;
      owl:onProperty ex:hasVehicle ;
      owl:someValuesFrom ex:SedanVehicle ;
    ] ;

But, back to your update process.  I seems this is where things are going awry.  Gist is pretty small, couldn't an approach be to delete the previous Gist instances and replace with the new ones?  (I'm assuming either way you need to run a compatibility check to see if the new version breaks anything.)
.

**Comment by DougalW** [comment] 2020-06-07 23:21
> After looking at our OWL, I'm wondering if this isn't a stylistic problem. Ignoring isIdentifiedBy and madeUpOf, we have
> 
> ```
> <owl:Class rdf:about="&gist;PhysicalIdentifiableItem">
>         <rdfs:subClassOf>
>                 <owl:Restriction>
>                         <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
>                         <owl:someValuesFrom rdf:resource="&gist;Volume"/>
>                 </owl:Restriction>
>         </rdfs:subClassOf>
>         <rdfs:subClassOf>
>                 <owl:Restriction>
>                         <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
>                         <owl:someValuesFrom rdf:resource="&gist;Weight"/>
>                 </owl:Restriction>
>         </rdfs:subClassOf>
> <owl:Class>
> ```
> 
> Would your problem be fixed if this were changed to the semantically identical, stylistically different version below?
> 
> ```
> <owl:Class rdf:about="&gist;PhysicalIdentifiableItem">
>         <rdfs:subClassOf>
>                 <owl:Class>
>                         <owl:intersectionOf rdf:parseType="Collection">
>                                 <owl:Restriction>
>                                         <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
>                                         <owl:someValuesFrom rdf:resource="&gist;Volume"/>
>                                 </owl:Restriction>
>                                 <owl:Restriction>
>                                         <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
>                                         <owl:someValuesFrom rdf:resource="&gist;Weight"/>
>                                 </owl:Restriction>
>                         </owl:intersectionOf>
>                 </owl:Class>
>         </rdfs:subClassOf>
> </owl:Class>
> ```
> 
> I'm still not agreeing in principle that the ontology should be written to suit the needs of specific software applications, and it would most likely be difficult to consistently maintain one of these stylistic variants over the other in the course of future development, but I'm curious whether this would fix it. Personally I have a stylistic preference for the second version, but that's beside the point.

Thanks for that. I'll modify a local copy of GIST top to this version of PhysicallyIdentifiableItem and experiment to see if that solves it.

**Comment by DougalW** [comment] 2020-06-07 23:26
> @DougalW I haven't had time to digest your comments so I don't have a well thought out response to your situation. I'd be happy to have a call with you to discuss.
> 
> As for how we handle the problem in our data-centric architecture, probably the biggest one is we don't try to map RDF/OWL to OO classes or strongly typed programming constructs. The goal is to interpret the data as it exists at any point in time. It should be able to support any possible RDF construct.
> 
> As Michael said, there is an impedance mismatch between RDF/OWL's relationships and strongly typed object oriented programming. As you mentioned, there are ways around it, but the two worlds don't map well because they are fundamentally different. If you want to support all of the flexibility of RDF/OWL then your code has to be able to handle the fact that RDF/OWL lets you do this. It isn't that you can't handle it with Java, its that you have to write your software to handle it.
> 
> It sounds like your parsing isn't building the context it needs to properly interpret the data. You can't treat a few triples in isolation.
> 
> A reason you may not have experienced this problem much with other ontologies is that many Ontologists think somewhat from an OO or Relational data modeling perspective because that is what has been standard practice for so long. [Or even that some internal Ontologies are derived from an existing relational models.] They will create multiple properties that fundamentally have the same meaning but connect different things. They probably think this is easier to understand. The result is you end up with 10's to 100's of thousands of terms, which is not digestible by a developer in a reasonable amount of time. I will go so far as to say that is probably an anti-pattern from Semantic Arts' perspective. If you have code behind every ontology term this results in code bloat and complexity. All of which increases maintenance and integration costs in the long run.
> 
> (Nearly) Anything is possible with software, I'd guess we can find a solution to handle this case in Java.

Thanks for your reply Jamie. I think a call would be good - what time zone are you in? We're based in New Zealand so our timezone is UTC+12.

**Comment by DougalW** [comment] 2020-06-07 23:31
> @DougalW I'm wondering if your issue is really with the schema service that uses your "schema service uses Jena to update an in-memory object-oriented representation of the ontology that is suitable for use by Java and our front-end". I.e. Jena may fail on the multiple object properties with different class values. Perhaps it is assuming that these are transformed into the single object property/value pairs for processing (using `and` in this case)? It may be worth exploring Jena and Jena forums to see if others have similar issues.
> 
> The bottom line is that Gist is using a perfectly valid form of OWL that expresses various constraints of values of an object property. For example, if you wanted to define a SuburbanPerson as a class of individuals that have at least one 4-wheel vehicle and one sedan vehicle, then this could be expressed as follows (in Turtle):
> 
> ```
> ex:SuburbanPerson
>   rdf:type owl:Class ;
>   rdfs:subClassOf ex:Person ;
>   rdfs:subClassOf [
>       rdf:type owl:Restriction ;
>       owl:onProperty ex:hasVehicle ;
>       owl:someValuesFrom ex:FourWheelVehicle ;
>     ] ;
>   rdfs:subClassOf [
>       rdf:type owl:Restriction ;
>       owl:onProperty ex:hasVehicle ;
>       owl:someValuesFrom ex:SedanVehicle ;
>     ] ;
> ```
> 
> But, back to your update process. It seems this is where things are going awry. Gist is pretty small, couldn't an approach be to delete the previous Gist instances and replace with the new ones? (I'm assuming either way you need to run a compatibility check to see if the new version breaks anything.)

Hi Scott, thanks for your comments. We aim to follow data centric principles everywhere, and we load and validate the most current releases of GIST. It's really only multiple instances of the same object property that give us this issue.

**Comment by Jamie-SA** [comment] 2020-06-09 15:01
> Thanks for your reply Jamie. I think a call would be good - what time zone are you in? We're based in New Zealand so our timezone is UTC+12.

@DougalW my timezone is GMT-6. So I think 10 am your time would be 4pm my time. My phone email address is jamie.gulden@semanticarts.com.

This should send you an email, I will remove my email info afterwards.

**Comment by rjyounes** [comment] 2020-06-11 16:04
We've agreed internally that this is a programming issue rather than a gist issue, so closing this ticket. @DougalW will follow up with @Jamie-SA and perhaps others for tech support.

**Closed** 2020-06-11 17:18 UTC
Labels: closed: invalid
