### ISSUE TITLE
gist:OrderedCollection has no ordering mechanism ?

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#114] opened 2019-09-24 05:42 UTC
I do not see that gist:OrderedCollection defines a mechanism for specifying an order. Does that mean that it is left up to the implementation to define how to establish order? Or am I missing something?

From a Data Centric Architecture point of view, an ordered collection is a bit useless without a defined ordering mechanism.

Why is there an ordering mechanism on gist:OrdinalCollection but not gist:OrderedCollection? 

To put an ordering mechanism in place I can think of two existing examples:
1) use rdf:Seq and/or rdf:_1 in some manner

2) move the ordering mechanism of gist:OrdinalCollection up to gist:OrderedCollection? Meaning gist:directlyPrecedes and gist:directlyPrecededBy have owl:someValuesFrom a new class gist:OrderedMember and deprecate gist:OrdinalMember (or make it a rdfs:subPropertyOf gist:OrderedMember)??

The discussion on issue #112 is also relevant.

**Comment by rjyounes** [comment] 2020-07-08 16:24
Does this issue include anything that's not in #112? If not, I suggest closing it.

**Comment by uscholdm** [comment] 2020-07-08 22:14
I agree. Just make sure to point back to this issue (114).

**Comment by rjyounes** [comment] 2020-07-08 22:18
Duplicate of #112, which is broader.

**Closed by rjyounes** 2020-07-08 22:18 UTC
Labels: closed: duplicate, topic: collections
