### ISSUE TITLE
Change hasUoM to hasUnitOfMeasure

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#144] opened 2020-01-15 19:48 UTC
(and deprecate hasUoM). This is a constant source of aggravation, since the class is UnitOfMeasure. I would at least expect hasUofM, but even that is hard to remember.

When we deprecate hasUoM we should create an equivalent property relationship to the new property. This also helps document the change so that if there are cascading changes we can make them when the deprecated property is removed.

**Comment by stewardont** [comment] 2020-01-16 15:02
Duplicate of issue #108.

We might want to address all the open issues related to units of measure (#75, #84, #91) at the same time.

**Comment by rjyounes** [comment] 2020-01-16 15:17
Closed #108. The other issues are different, ranging from typos to substance, so I don't see a need to manage them together.

**Comment by uscholdm** [comment] 2020-01-16 23:47
Rebecca said: 
>  This is a constant source of aggravation, since the class is UnitOfMeasure
Yeah: hasUnitOfMeasure some UnitOfMeasure is annoying. But it can be fixed by using a Magnitude as a unit of measure. A meter is a meter is a meter whether it is used as a unit or not. This was discussed in another issue, which I cannot find at the moment.

**Comment by rjyounes** [comment] 2020-01-16 23:53
I think you're referring to #61, and I agree with you. I meant something far more trivial, that because the names of class and property are inconsistent, I couldn't remember which was which.

**Comment by sa-bpelakh** [comment] 2021-03-25 15:36
Can be done as part of https://github.com/semanticarts/gist/issues/188.

**Closed by sa-bpelakh** 2021-03-25 15:36 UTC
Labels: closed: duplicate, topic: units and measures
