### ISSUE TITLE
Thorough refresh of gist annotations.

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#159] opened 2020-01-29 18:38 UTC
Jonathon Storm sent a proposed set of revised annotations.   I put them in a new Development folder in the shared drive.
s:\Offerings\gist\Development\
 
If anyone knows how to put this up on Office 360, we can all collaboratively edit it there.

**Comment by rjyounes** [comment] 2020-05-04 14:54
Duplicate of #217.

**Closed by rjyounes** 2020-05-04 14:54 UTC
Labels: closed: duplicate
