### ISSUE TITLE
Version tag standardization

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#445] opened 2021-03-17 19:05 UTC
The developer in me wants consistent tags on our releases. The last release got tagged with a different format. 
```
$> git tag
9.5.0
v8.0.0
v9.0.0
v9.1.0
v9.2.0
v9.3.0
v9.4.0
```
I don't know if we have documented what the tag should look like.
Is adding the tag automated or is it still manual?

Visually I like the "v" in front of the semver number, but if it wasn't there then it could be used directly to replace the "X.x.x" in the release process and other scripts (for automated tests, deploy scripts, etc).

**Comment by rjyounes** [comment] 2021-03-17 21:05
The correct format is v9.5.0. It is documented here:  https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists.

It is still manual. The release manager should do a GitHub release and specify the name of the tag.

**Comment by rjyounes** [comment] 2021-03-17 21:11
However, I'm looking at the [releases](https://github.com/semanticarts/gist/releases) and see it tagged as v9.6.0. When I run `git tag` I get:
```
v8.0.0
v9.0.0
v9.1.0
v9.2.0
v9.3.0
v9.4.0
v9.5.0
v9.6.0
```
Releases are named "9.6.0" etc. and I wonder if that should be changed to "v9.6.0" as well.

**Comment by rjyounes** [comment] 2021-03-17 21:22
Closing - can't reproduce.

**Closed by rjyounes** 2021-03-17 21:22 UTC
Labels: closed: can't reproduce
