### ISSUE TITLE
Does the serializer give different results on a Protégé-generated file?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#646] opened 2022-03-18 13:59 UTC
We've observed some differences in serialization output from commit to commit, generally having to do with ordering of triples. One hypothesis is that the serializer is producing different results on Protégé-generated files and manually edited files (for reasons unknown). The task is to run an experiment to determine whether this is true, and if so, figure out what if anything can be done about it.

**Comment by wslooney** [comment] 2022-03-23 21:09
I ran some experiments editing gist in a text editor and in Protégé then running both through the serializer. Here are a few discoveries.

**1**
The serializer appears leave everything in parentheses in the order it finds it but Protégé does not. Two examples: 
1. Protégé will alphabetize the members of an enumerated list, but the serializer won't. 
2. If we declare a class equivalent to the intersection of some class restriction and some declared class, Protégé re-orders it to put the declared class in front of the class restriction.
So this means that the file output from Protégé will end up different even after it goes through the serializer.

**2**
There were also some differences in the first 20 or so lines. Protégé added:
@prefix : <https://ontologies.semanticarts.com/o/gistCore#> .

**3**
Protégé made all 4 of the skos annotations used explicit, e.g., 
skos:definition
	a owl:AnnotationProperty 
	.

**4**
The weirdest difference was that Protege removed the following line(13):
	skos:prefLabel "gist Core"^^xsd:string ;
from the predicates for the Ontology itself.

**Comment by wslooney** [comment] 2022-03-23 21:10
I run some more experiments tomorrow trying to create the same issue that happened inside of parentheses with other constructions not in parentheses.

**Comment by wslooney** [comment] 2022-03-24 14:05
I run a bunch of other experiments this morning, and I'm pretty sure it's just objects inside of parentheses that are causing issues. As an example if we put this into the serializer

`gist:Event
	a owl:Class ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			[
				a owl:Restriction ;
				owl:onProperty gist:isCharacterizedAs ;
				owl:someValuesFrom gist:Behavior ;
			]

			[
				a owl:Restriction ;
				owl:onProperty gist:startDateTime ;
				owl:cardinality "1"^^xsd:nonNegativeInteger ;
			]

			[
				a owl:Restriction ;
				owl:onProperty gist:endDateTime ;
				owl:cardinality "1"^^xsd:nonNegativeInteger ;
			]

		) ;
	] ;
	skos:definition "Something that occurs over some period of time, often characterized as an activity being carried out by some person, organization, or software application."^^xsd:string ;
	skos:prefLabel "Event"^^xsd:string ;
	.`
	
It leaves everything as is. But run it through Protege and then the serializer and Protege will rearrange the class restrictions the following way in order to alphabetize where possible:

```
		owl:intersectionOf (
			[
				a owl:Restriction ;
				owl:onProperty gist:isCharacterizedAs ;
				owl:someValuesFrom gist:Behavior ;
			]
			[
				a owl:Restriction ;
				owl:onProperty gist:endDateTime ;
				owl:cardinality "1"^^xsd:nonNegativeInteger ;
			]
			[
				a owl:Restriction ;
				owl:onProperty gist:startDateTime ;
				owl:cardinality "1"^^xsd:nonNegativeInteger ;
			]
		) ;
```

**Comment by wslooney** [comment] 2022-03-24 17:40
I've found some more where it enforces an order, but not one I'd have anticipated. Thanks for pointing this out. I'll try and figure it out.

**Comment by wslooney** [comment] 2022-03-24 18:55
It seems to put restrictions on dataproperties below object properties. I'm not sure how it's ordering beyond that.

I'm not sure understanding it is going to solve _our_ problem though. I raised an issue in the rdf-toolkit github that their serializer seems to be leaving everything as is, in these instances. Maybe they'll have a solution.

**Comment by wslooney** [comment] 2022-04-14 15:58
While someone was assigned to the issue, it hasn't been addressed (https://github.com/edmcouncil/rdf-toolkit/issues/20). I commented this morning, but @Jamie-SA suggested possibly looking into creating a PR there.

**Comment by rjyounes** [comment] 2022-04-28 15:22
Protege orders items in parentheses (unions or intersections) and the serializer doesn't. Therefore, the serializer output is different for files edited in Protege vs hand-edited.

We will do a one-time Protege + serializer commit to normalize the current version of gist. This has to be re-done by Protege users if new restrictions or other elements are added within parentheses.

**Comment by rjyounes** [comment] 2022-04-28 16:21
New issue to add note to Contributing.md and style guide for Protege users: #665.

**Comment by Jamie-SA** [comment] 2022-08-01 15:45
Not sure if this is obvious but I haven't seen it mentioned yet. WRT the issue of ordering the lists (those things/triples inside of parenthesis in Turtle files) probably comes down to this:
- A RDF list is an ordered list. Whether the order is important or not depends on the data. The serializer is meant to be a generic tool, not specific to OWL files. It does not change the order of RDF lists, it maintains the order, because it doesn't know that in this case the order is not important.
- protege probably has it's own internal data structure for everything and outputs it in the order it wants. Looking at it from another perspective, protege has knowledge about the data inside the RDF lists and knows that the order is not important so it doesn't try to preserve the order in OWL lists.

Therefore, I'm guessing that the authors of the serializer would decide that they should not reorder lists.

Possible option: Is there is an easy set of rules that non-protege users could use to order lists/restrictions before passing it to the serializer.

**Comment by rjyounes** [comment] 2022-08-12 18:42
This makes sense. I'm afraid your last sentence is going to start a war. Why not an easy set of rules that protege users could use to order lists/restrictions after exporting it from protege and passing it to the serializer?

**Comment by Jamie-SA** [comment] 2022-08-12 19:35
Because you can't control Protege, it will do what it does. If you want a different order than what Protege produces it will require hand editing after saving from Protege to get a proper "diff". OTOH, the serializer seems to accept whatever list order it is given so there is no clean up required.

So, said another way, accepting Protege's order means less work overall. No extra work for Protege users. A little mental work to order correctly by non-protege users the first time something is written or when editing.

Another option would be to use Protege (or it's libraries so it can be automated) as the serializer, then a step to remove the Protege added stuff (not sure if that is already automated). Then there would be no extra work once the switch is made.

**Comment by rjyounes** [comment] 2022-08-12 19:46
My comment was a bit tongue-in-cheek. I would be fine with ordering them in whatever way protege does, or continuing to ignore those diffs as we have been doing and closing this issue.

**Comment by marksem** [comment] 2022-09-17 18:34
**BLUF** ((bottom Line Up Front)

**Recommendations:**

1. I believe OrderedCollection should be changed in gistCore.ttl, with the type of the bnode stated, as we do with every other union in gistCore.ttl.

1. I believe we should do a 1-time reformat of gistCore with Protege to get the ordering of property restrictions more deterministic.  This would address gist:HistoricalEvent and gist:TreatyOrganization mentioned above. 

1. OPTIONAL:  Would it be so wrong to add the 4 skos declarations at the top?  We do use them extensively.  And it would stop Protege from dropping the ontology's pref label.  And stop Protege users from having to do special edits post-serializer.  And, these declarations are not logically incorrect.  And non-protege editors can ignore them.  


**Full Analysis**


Let's capture what the format is now

	cp -p gistCore.ttl origGistCore.ttl

Then made a small protege edit (just the version iri)

Save a copy of that format:

	cp -p gistCore.ttl protGistCore.ttl

Run serializer on the edited file:

	$ tools/serialize gistCore.ttl
	serializing gistCore.ttl
	Reserializing gistCore.ttl into a standard format.
	Done!

Q: How do things look?
A: Oof!  Big diff!  Even if we ignore Protege's adding of the 4 skos:definitions at the top.

	$ diff origGistCore.ttl gistCore.ttl
	12c12
	<       owl:versionIRI <https://ontologies.semanticarts.com/o/gistCoreX.x.x> ;
	---
	>       owl:versionIRI <https://ontologies.semanticarts.com/o/gistCoreX.x.y> ;
	14d13
	<       skos:prefLabel "gist"^^xsd:string ;
	17a17,32
	> skos:definition
	>       a owl:AnnotationProperty ;
	>       .
	>
	> skos:example
	>       a owl:AnnotationProperty ;
	>       .
	>
	> skos:prefLabel
	>       a owl:AnnotationProperty ;
	>       .
	>
	> skos:scopeNote
	>       a owl:AnnotationProperty ;
	>       .
	>
	1163c1178
	<                               owl:onProperty gist:actualStartDateTime ;
	---
	>                               owl:onProperty gist:actualEndDateTime ;
	1168c1183
	<                               owl:onProperty gist:actualEndDateTime ;
	---
	>                               owl:onProperty gist:actualStartDateTime ;
	1711,1715c1726
	<                               a owl:Restriction ;
	<                               owl:onProperty gist:hasMember ;
	<                               owl:allValuesFrom gist:OrderedMember ;
	<                       ]
	<                       [
	---
	>                               a owl:Class ;
	1719,1720c1730,1731
	<                                               owl:onProperty gist:hasMember ;
	<                                               owl:cardinality "0"^^xsd:nonNegativeInteger ;
	---
	>                                               owl:onProperty gist:hasFirstMember ;
	>                                               owl:someValuesFrom owl:Thing ;
	1724,1725c1735,1736
	<                                               owl:onProperty gist:hasFirstMember ;
	<                                               owl:someValuesFrom owl:Thing ;
	---
	>                                               owl:onProperty gist:hasMember ;
	>                                               owl:cardinality "0"^^xsd:nonNegativeInteger ;
	1728a1740,1744
	>                       [
	>                               a owl:Restriction ;
	>                               owl:onProperty gist:hasMember ;
	>                               owl:allValuesFrom gist:OrderedMember ;
	>                       ]
	2507c2523
	<                               owl:minCardinality "2"^^xsd:nonNegativeInteger ;
	---
	>                               owl:allValuesFrom gist:CountryGovernment ;
	2512c2528
	<                               owl:allValuesFrom gist:CountryGovernment ;
	---
	>                               owl:minCardinality "2"^^xsd:nonNegativeInteger ;



[Side note: serializer does tabs, whereas there’s a clear preference for spaces over tabs in the style guides. See [https://www.overops.com/blog/tabs-vs-spaces-how-they-write-java-in-google-twitter-mozilla-and-pied-piper/](https://www.overops.com/blog/tabs-vs-spaces-how-they-write-java-in-google-twitter-mozilla-and-pied-piper/) ]

Do sdiff to better see what changed 

	sed 's/\t/  /g' origGistCore.ttl > 2origGistCore.ttl
	sed 's/\t/  /g' gistCore.ttl > 2gistCore.ttl
	sdiff -w 200 2origGistCore.ttl 2gistCore.ttl > xx


Observations in file xx:

1. INTERESTING:  Protege does not show/render nor save the skos:prefLabe on the ontology IRI. 
   (Further tests showed this behavior does not happen if skos:prefLabel is declared in the file.)

1. Protege adds the 4 undeclared skos properties at top.  Known/expected behavior. 

1. gist:HistoricalEvent gets formatted differently.  The property restrictions are ordered alphabetically, whereas in the original gistCore.ttl file, they were not.

1. gist:TreatyOrganization gets formatted differently.  The property restrictions are ordered differently, with allValuesFrom before minCardinality (apparently alphabetically)

1. gist:OrderedCollection gets formatted differently because it is ENCODED differently. It is encoded by Protege as: 

- equivalent to an owl:Class that is intersection of a list, where in the list are:   

	1) a gist:Collection, 
	2) an owl:Class that is a unionOf 2 owl:Restrictions, and 
	3) an owl:Restriction (onProperty)

whereas in the original gistCore.ttl file, this was modeled as:

- equivalent to an owl:Class that is intersection of a list, where in the list are:   

	1) a gist:Collection, 
	2) an UNTYPED BNODE (!) that is a unionOf 2 owl:Restrictions 
	3) an owl:Restriction (onProperty)   (BUT MOVED TO 2nd IN THE ORDER)

**Comment by rjyounes** [comment] 2022-09-18 17:54
I am opposed to declaring a term that is not in our namespace.

**Comment by Jamie-SA** [comment] 2022-09-19 15:56
Would Protege stop adding the declarations if there was an `import` for the SKOS ontology?

**Comment by marksem** [comment] 2022-09-20 11:21
Yes I think it would.

**Comment by marksem** [comment] 2022-09-20 11:28
Humorously, these get added anyway in the all of the Widoco versions of gist.  :D   Probably b/c we use OWL API, same as Protege.  Ref. https://gist-doc.semanticarts.com/gist-11.0/widoco-documentation/index-en.html and click on each format.  You can't fight city hall. :D

**Comment by uscholdm** [comment] 2022-09-23 15:54
> Would Protege stop adding the declarations if there was an `import` for the SKOS ontology?

That has been my experience. I have not tested it recently, but there has been no new version of Protege for years now.

**Comment by rjyounes** [comment] 2022-09-26 20:38
Is the proposal to add an import of SKOS to gist? It would be a nice convenience to get rid of those stubs, but on the other hand might seem weird because we are not using any SKOS axioms, only annotations.

**Comment by uscholdm** [comment] 2022-09-26 22:14
> Is the proposal to add an import of SKOS to gist?

It's a possibility with pros and cons.

**Comment by uscholdm** [comment] 2023-11-09 18:37
@rjyounes, @wslooney, @marksem, @Jamie-SA 
This was a long, interesting thread full of examples and technical details. Is this still something we can do something about - or shall we close the issue?

**Comment by marksem** [comment] 2023-11-13 21:38
Ah, this was a good ole issue.  But I think we can close it now.  It had a long and productive life.

**Comment by rjyounes** [comment] 2023-11-16 23:04
Closing.

**Closed** 2023-12-29 13:10 UTC
Labels: status: implementation specified, area: infrastructure
