### ISSUE TITLE
Definition of gist:Area limited to rectangles

### ISSUE THREAD

**Issue by scotthenninger** [semanticarts/gist#331] opened 2020-07-09 15:53 UTC
Unless I'm mistaken, gist:Area is currently defined as equivalent to gist:AreaUnit, which is a gist:ProductUnit type that takes a gist:multiplicand and gist:multiplier.  This limits the definition of an area to rectangles, and can't be used to define the area of say, a country, or even a circle.  Furthermore, in cases where an area is reported in the original data as square metres, square meters, etc., there isn't a way to deconstruct that into a multiplicand and multiplier.

The same issue occurs with volume, which is defined as AreaUnit x DistanceUnit.

I'd like to suggest that the definitions allow a gist:BaseUnit measure, and that the instances of gist_:square_metre and gist:_cubic_metre, which are the SI units for area and volume, be added to gist:BaseUnit.

**Comment by daliadahleh** [comment] 2020-07-09 16:29
I don't see why this limits gist:AreaUnit, or gist:Area, to rectangles. The multiplicand and multiplier in this case are the distance _units_ (eg. meter), not the physical distance (eg. a side of a rectangle). The area of a circle, or the area of a country, can still be measured in square meters, even if you're not multiplying two distances together to calculate the area.

gist:Area is not equivalent to gist:AreaUnit. gist:Area is any magnitude (eg. circle) which has a unit of measure that is a gist:AreaUnit (eg. square meters).

**Comment by daliadahleh** [comment] 2020-07-09 17:19
> Furthermore, in cases where an area is reported in the original data as square metres, square meters, etc., there isn't a way to deconstruct that into a multiplicand and multiplier.

I'm not entirely sure I understand what you meant by this part. Is the issue that the multiplicand and multiplier are the same? If so, that's not a problem. This is actually the reason for having gist:multiplicand and gist:multiplier, rather than using gist:multiplier twice. It allows you to use the same unit for both (`:_square_meter gist:multiplier gist:_meter` is one triple, and a duplicate of it wouldn't mean anything, but `:_square_meter gist:multipicand gist:_meter` adds the second part of the equation).

> I'd like to suggest that the definitions allow a gist:BaseUnit measure, and that the instances of gist_:square_metre and gist:_cubic_metre, which are the SI units for area and volume, be added to gist:BaseUnit.

If you look at [a definition](https://en.wikipedia.org/wiki/Base_unit_(measurement)) of base units, they are specifically for base quantities. You might be looking for gist:CoherentProductUnit, which is defined as a product unit whose multiplier and multiplicand are base units. :_square_meter would be a gist:CoherentProductUnit.

**Comment by uscholdm** [comment] 2020-07-09 18:16
> I'd like to suggest that the definitions allow a gist:BaseUnit measure, and that the instances of gist_:square_metre and gist:_cubic_metre, which are the SI units for area and volume, be added to gist:BaseUnit.

@daliadahleh 's Is correct.  A coherent unit (a physics or math term - I was calling them 'standard unit' before I learned the proper term) is one whose with conversion as 1. So square meter is one, but not square mile.  Meters per second is one, but not kilometers per hour.

**Comment by scotthenninger** [comment] 2020-07-09 18:33
I am looking at gist:CoherentProductUnit, but I don't see a reason to use that, particularly given the SI units, which are referenced for ampere, kilogram, etc, includes square metre and cubic metre.  Hence onc can reasonably conclude that these are base units.  Adding a multiplier and multiplicand just seems to add complexity where none is needed.

Maybe a question is needed here.  What advantage do you get by requiring a multiplier and multiplicand?

**Comment by daliadahleh** [comment] 2020-07-09 19:56
> Hence onc can reasonably conclude that these are base units

There are only [7 SI base units](https://en.wikipedia.org/wiki/SI_base_unit#Definitions) for the [7 base quantities](https://en.wikipedia.org/wiki/International_System_of_Quantities#Base_quantities). These are standard scientific definitions, it's not up to us to change them.

**Comment by scotthenninger** [comment] 2020-07-09 20:57
But they do define coherent units, but not in terms of a derivation - https://en.wikipedia.org/wiki/International_System_of_Units.

**Comment by uscholdm** [comment] 2022-05-13 01:30
I propose that we close this issue. The main claim is false.  There remains a question about the utility of having a class called CoherentProductUnit, which should be in another issue - I think it may be already. If not, then it can be rolled into the broader issue to refactor units and magnitudes.

**Comment by rjyounes** [comment] 2022-05-13 13:40
Closed as per Michael's comment, and rolled into existing issue #146, whose title has been modified.

**Closed by rjyounes** 2022-05-13 13:40 UTC
Labels: closed: invalid, status: in review, topic: units and measures
