### ISSUE TITLE
Adapt tools/setup.sh for Windows users

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#797] opened 2023-02-23 14:18 UTC
The script `<root>/tools/setup.sh` is to be the first time you pull from develop since the merge of PR #795 (on 2/22), due to changes made in the pre-commit setup.

The script runs natively on Mac and Linux. Windows users must either:

* Manually copy `<root>/tools/pre-commit` to `<root>/.git/hooks`, or
* Use a bash shell available through VSCode, Git bash, etc.

@Jamie-SA is working on a solution that will provide a single script that will run natively on all three OSs.

**Comment by Jamie-SA** [comment] 2023-02-23 19:20
Is this a duplicate of #796?

**Comment by rjyounes** [comment] 2023-02-24 22:37
Yes, a duplicate. If you don't mind, I'll close #796, since this provides a bit more context.

**Comment by Jamie-SA** [comment] 2023-02-25 21:08
I've worked on the script and will submit a PR. But I'm wondering, the pre-commit script itself is a unix style shell script. In order for it to run on windows you need something like git-bash. So I'm wondering if a version of setup that runs as a Windows command shell is needed.

Can any ontologist working on Windows OS confirm or deny the need for a different version of the setup script?

**Comment by dylan-sa** [comment] 2023-02-27 14:11
> Can any ontologist working on Windows OS confirm or deny the need for a different version of the setup script?

Just one person's test here, but in my Windows environment `setup.sh` did not work in CMD or Powershell. It did work (as expected) with GitBash.

**Comment by Jamie-SA** [comment] 2023-03-03 02:30
Thanks Dylan.

I guess my question comes down to whether, if you are using `git` on Windows, does that mean you have `git-bash` or another linux like shell?

I did submit a PR to change the script to work on both linux and Windows command shell. So anyone interested can check out that PR and test it. #798

**Comment by dylan-sa** [comment] 2023-03-03 14:28
Right, the git bash emulator comes along with git for Windows. So even without the new `setup.cmd` file, most Windows users should be able to use git bash to run the `setup.sh` script currently on `develop`. I'm sure it would still be helpful to have a version that runs with CMD or PowerShell, though, as `setup.cmd` in #798 does.

**Closed** 2023-03-05 12:33 UTC
